def create_objects_dict(
    result_texts,
    champion,
    kill,
    death,
    assist,
    damage_dealt,
    damage_taken,
    game_type,
    length,
    percentage,
    tier,
    cs,
    cs_per_minute,
    game_items,
    wards,
    baron,
    dragon,
    tower,
):
    return {
        "result": result_texts,
        "champion": champion,
        "kill": kill,
        "death": death,
        "assist": assist,
        "dmg_dealt": damage_dealt,
        "dmg_taken": damage_taken,
        "game_type": game_type,
        "length": length,
        "kill_percentage": percentage,
        "average_tier": tier,
        "cs": cs,
        "cs_per_minute": cs_per_minute,
        "items": game_items,
        "control_wards": wards,
        "baron": baron,
        "dragon": dragon,
        "tower": tower,
    }
